name: CI
on: push
jobs:
  all:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.9
      - name: install
        run: npm --unsafe-perm install
      - name: format
        run: npm --unsafe-perm run format
      - name: lint
        run: npm --unsafe-perm run lint
      - name: test
        run: npm --unsafe-perm run test
      - name: prepublish
        run: scripts/prepublish
      - uses: primer/publish@master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
