name: CI
on: push
jobs:
  all:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.9
          registry-url: https://npm.pkg.github.com/
          scope: "@paquette"
      - name: install
        run: npm --unsafe-perm install
      - name: format
        run: npm --unsafe-perm run format
      - name: lint
        run: npm --unsafe-perm run lint
      - name: test
        run: npm --unsafe-perm run test
      - name: prepublish
        run: scripts/prepublish
      # Required due to bug.
      # See https://github.com/actions/setup-node/issues/52
      - name: set .npmrc
        run: printf "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n@paquette:registry=https://npm.pkg.github.com/" > ~/.npmrc
      - uses: primer/publish@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_REGISTRY_URL: ${{ secrets.NPM_REGISTRY_URL }}
